import UiUxDesigner from "../../../../../public/assets/PlacementImages/UiUxDesigner.webp"

const PlacedStudentsData = [
  {
    id: 1,
    profilePic: "/assets/PlacementImages/aibuzz.webp",
    username: "Priyansh Devada",
    logo: "/assets/PlacementImages/aibuzz.webp",
    companyName: "aibuzz",
    role: "UI-UX Designer",
  },
  {
    id: 2,
    profilePic: "/assets/PlacementImages/FullStackDeveloper.webp",
    username: "Sonam Kamble",
    logo: "/assets/PlacementImages/ashdip.webp",
    companyName: "ashdip",
    role: "Full Stack Developer",
  },
  {
    id: 3,
    profilePic: "/assets/PlacementImages/EquityAnalyst.webp",
    username: "Rajveer Patil",
    logo: "/assets/PlacementImages/gemscap.webp",
    companyName: "gemscap",
    role: "Equity Analyst",
  },
  {
    id: 4,
    profilePic: "/assets/PlacementImages/ReactjsDeveloper.webp",
    username: "Aniket Milmile",
    logo: "/assets/PlacementImages/rubicon.webp",
    companyName: "rubicon",
    role: "ReactJs Developer",
  },
  {
    id: 6,
    profilePic: "/assets/PlacementImages/DataEngineer.webp",
    username: "Ishant Patil",
    logo: "/assets/PlacementImages/nablainfotech.webp",
    companyName: "nablainfotech",
    role: "Data Engineer",
  },
  {
    id: 7,
    profilePic: "/assets/PlacementImages/DevopsTrainee.webp",
    username: "Bhavesh Jadhav",
    logo: "/assets/PlacementImages/infogain.webp",
    companyName: "infogain",
    role: "DevOps Trainee",
  },
  {
    id: 8,
    profilePic: "/assets/PlacementImages/TechnicalSupport.webp",
    username: "Kuldeep Patil",
    logo: "/assets/PlacementImages/leapot.webp",
    companyName: "leapot",
    role: "Technical Support",
  },
  {
    id: 9,
    profilePic: "/assets/PlacementImages/nodejsintern.webp",
    username: "Manish Yelem",
    logo: "/assets/PlacementImages/ovtpl1.webp",
    companyName: "ovtpl1",
    role: "Node.js Intern",
  },
  {
    id: 10,
    profilePic: "/assets/PlacementImages/HTMLDeveloper.webp",
    username: "Mohasin Attar",
    logo: "/assets/PlacementImages/transparency.webp",
    companyName: "transparency",
    role: "HTML Developer",
  },
  {
    id: 11,
    profilePic: "/assets/PlacementImages/ITSupport.webp",
    username: "Rohit Joshi",
    logo: "/assets/PlacementImages/hbfuller.webp",
    companyName: "hbfuller",
    role: "IT Support",
  },
  {
    id: 12,
    profilePic: "/assets/PlacementImages/Dataengine.webp",
    username: "Rutika Pawar",
    logo: "/assets/PlacementImages/nablainfotech.webp",
    companyName: "nablainfotech",
    role: "Data Engineer",
  },
  {
    id: 13,
    profilePic: "/assets/PlacementImages/HRRecuiter.webp",
    username: "Tejaswini Ingle",
    logo: "/assets/PlacementImages/kvstaffingservices.webp",
    companyName: "kvstaffingservices",
    role: "HR Recruiter",
  },
  {
    id: 14,
    profilePic: "/assets/PlacementImages/DataScientist.webp",
    username: "Vaishnavi Sonar",
    logo: "/assets/PlacementImages/bulfro.webp",
    companyName: "bulfro",
    role: "Data Scientist Intern",
  },
  {
    id: 15,
    profilePic: "/assets/PlacementImages/SapExecutive.webp",
    username: "Yash Kurhade",
    logo: "/assets/PlacementImages/faber.webp",
    companyName: "faber",
    role: "SAP Sr. Executive",
  },
  {
    id: 16,
    profilePic: "/assets/PlacementImages/ITDepartment.webp",
    username: "Priyanka Jyoti",
    logo: "/assets/PlacementImages/tatacommunications.webp",
    companyName: "tatacommunications",
    role: "IT Support",
  },
  {
    id: 17,
    profilePic: "/assets/PlacementImages/SoftwareDeveloper.webp",
    username: "Vinayak Sutar",
    logo: "/assets/PlacementImages/bulfro.webp",
    companyName: "bulfro",
    role: "Software Developer",
  },
  {
    id: 18,
    profilePic: "/assets/PlacementImages/CloudTraineeEng.webp",
    username: "Karan Nawale",
    logo: "/assets/PlacementImages/moschip.webp",
    companyName: "moschip",
    role: "Cloud Trainee Engineer",
  },
  {
    id: 19,
    profilePic: "/assets/PlacementImages/PayrollExecutive.webp",
    username: "Ashwini Akshay Swami",
    logo: "/assets/PlacementImages/TopsourceWorldwide.webp",
    companyName: "topsource",
    role: "Payroll Executive",
  },
  {
    id: 20,
    profilePic: "/assets/PlacementImages/AssociateEngineer.webp",
    username: "Rishabh Patond",
    logo: "/assets/PlacementImages/tatacommunications.webp",
    companyName: "tatacommunications",
    role: "Associate Engineer",
  },
  {
    id: 21,
    profilePic: "/assets/PlacementImages/MernStackDeveloperIntern.webp",
    username: "Abhijit Shirsath",
    logo: "/assets/PlacementImages/Provaantech.webp",
    companyName: "provsantech",
    role: "Mern Stack Developer Intern",
  },
  {
    id: 22,
    profilePic: "/assets/PlacementImages/ReactJSIntern.webp",
    username: "Abhishek Mane",
    logo: "/assets/PlacementImages/SevenMentor.webp",
    companyName: "sevenmentor",
    role: "React-JS Intern",
  },
  {
    id: 23,
    profilePic: "/assets/PlacementImages/PythonDeveloper.webp",
    username: "Ajay Kannojwar",
    logo: "/assets/PlacementImages/KarnexAutomotiveSoftwareSolutions.webp",
    companyName: "Karnex – Automotive Software Solutions",
    role: "Python Developer",
  },
  {
    id: 24,
    profilePic: "/assets/PlacementImages/InternAIMLDeveloper.webp",
    username: "Amit Khade",
    logo: "/assets/PlacementImages/Provaantech.webp",
    companyName: "Provaantech",
    role: " Intern AI ML Developer",
  },
  {
    id: 25,
    profilePic: "/assets/PlacementImages/TraineeSOCSupport.webp",
    username: "Bhavika Soni",
    logo: "/assets/PlacementImages/SystemsPlusPrivateLimited.webp",
    companyName: "Systems Plus Private Limited",
    role: "Trainee SOC Support",
  },
  {
    id: 26,
    profilePic: "/assets/PlacementImages/NocEngineer.webp",
    username: "Komal Maruti Shinde",
    logo: "/assets/PlacementImages/GracewayInfrastructure.webp",
    companyName: "Graceway Infrastructure",
    role: " Noc Engineer",
  },
  {
    id: 27,
    profilePic: "/assets/PlacementImages/DevOpsProfessional.webp",
    username: "Mahesh Bodkhe",
    logo: "/assets/PlacementImages/OffshoreITMitraPvtLtd.webp",
    companyName: "Offshore IT Mitra Pvt. Ltd",
    role: "DevOps Professional",
  },
  {
    id: 28,
    profilePic: "/assets/PlacementImages/UIUXDesignerIntern.webp",
    username: "Nikhil Solanki",
    logo: "/assets/PlacementImages/SevenMentor.webp",
    companyName: "SevenMentor Pvt. Ltd",
    role: "UI-UX Designer Intern",
  },
  {
    id: 29,
    profilePic: "/assets/PlacementImages/UIUX-DesignerIntern.webp",
    username: "Pornima Joshi",
    logo: "/assets/PlacementImages/CodingCultCommunity.webp",
    companyName: "Coding Cult Community",
    role: "UI-UX Designer Intern",
  },
  {
    id: 30,
    profilePic: "/assets/PlacementImages/Intern-AI-ML-developer.webp",
    username: "Pushpendra  Dhamanya",
    logo: "/assets/PlacementImages/Provaantech.webp",
    companyName: "Provaantech",
    role: "Intern AI ML Developer",
  },
  {
    id: 31,
    profilePic: "/assets/PlacementImages/Noc-Engineer.webp",
    username: "Rohit Vilas Londhe",
    logo: "/assets/PlacementImages/GracewayInfrastructure.webp",
    companyName: "Graceway Infrastructure",
    role: "Noc Engineer",
  },
  {
    id: 32,
    profilePic: "/assets/PlacementImages/TalentacquisitionSpecialist.webp",
    username: "Sagar Katkar",
    logo: "/assets/PlacementImages/kvstaffingservices.webp",
    companyName: "KV Staffing Services",
    role: "Talent Acquisition Specialist",
  },
  {
    id: 33,
    profilePic: "/assets/PlacementImages/AssociateELearningDeveloper.webp",
    username: "Suhani Khandelwal",
    logo: "/assets/PlacementImages/leapot.webp",
    companyName: "Leapot Technologies",
    role: "Associate eLearning Developer",
  },
  {
    id: 34,
    profilePic: "/assets/PlacementImages/Associate-Engineer.webp",
    username: "Suraj Chamate",
    logo: "/assets/PlacementImages/tatacommunications.webp",
    companyName: "Tata Communications",
    role: "Associate Engineer",
  },
  {
    id: 35,
    profilePic: "/assets/PlacementImages/Mern-stack-developer-intern.webp",
    username: "Akshada Khese",
    logo: "/assets/PlacementImages/Provaantech.webp",
    companyName: "Provaantech",
    role: "Mern Stack Developer Intern",
  },
  {
    id: 36,
    profilePic: "/assets/PlacementImages/Mernstack-developerintern.webp",
    username: "Akshay Gadade ",
    logo: "/assets/PlacementImages/Provaantech.webp",
    companyName: "Provaantech",
    role: "Mern Stack Developer Intern",
  },
  {
    id: 37,
    profilePic: "/assets/PlacementImages/UIUXdesigner-intern.webp",
    username: "Megha Nejkar",
    logo: "/assets/PlacementImages/Provaantech.webp",
    companyName: "Provaantech",
    role: "UI-UX Designer Intern",
  },
  {
    id: 38,
    profilePic: "/assets/PlacementImages/ui-uxdesignerintern.webp",
    username: "Path Ingle",
    logo: "/assets/PlacementImages/Provaantech.webp",
    companyName: "Provaantech",
    role: "UI-UX Designer Intern",
  },
  {
    id: 39,
    profilePic: "/assets/PlacementImages/uiux-designerIntern-.webp",
    username: "Akshi Karanjkar",
    logo: "/assets/PlacementImages/Provaantech.webp",
    companyName: "Provaantech",
    role: "UI-UX Designer Intern",
  },
  {
    id: 40,
    profilePic: "/assets/PlacementImages/uIuX-designer-Intern-.webp",
    username: "Sakshi Tamgade",
    logo: "/assets/PlacementImages/Provaantech.webp",
    companyName: "Provaantech",
    role: "UI-UX Designer Intern",
  },
];

export default PlacedStudentsData;
