
const PlacedStudentsData = [
  {
    id: 1,
    profilePic: "/assets/PlacementImages/UiUxDesigner.webp",
    username: "Priyansh Devada",
    logo: "/assets/PlacementImages/aibuzz.webp",
    companyName: "aibuzz",
    role: "UI-UX Designer",
  },
  {
    id: 2,
    profilePic: "/assets/PlacementImages/FullStackDeveloper.webp",
    username: "Sonam Kamble",
    logo: "/assets/PlacementImages/ashdip.webp",
    companyName: "ashdip",
    role: "Full Stack Developer",
  },
  {
    id: 3,
    profilePic: "/assets/PlacementImages/EquityAnalyst.webp",
    username: "Rajveer Patil",
    logo: "/assets/PlacementImages/gemscap.webp",
    companyName: "gemscap",
    role: "Equity Analyst",
  },
  {
    id: 4,
    profilePic: "/assets/PlacementImages/ReactjsDeveloper.webp",
    username: "Aniket Milmile",
    logo: "/assets/PlacementImages/rubicon.webp",
    companyName: "rubicon",
    role: "ReactJs Developer",
  },
  {
    id: 6,
    profilePic: "/assets/PlacementImages/DataEngineer.webp",
    username: "Ishant Patil",
    logo: "/assets/PlacementImages/nablainfotech.webp",
    companyName: "nablainfotech",
    role: "Data Engineer",
  },
  {
    id: 7,
    profilePic: "/assets/PlacementImages/DevopsTrainee.webp",
    username: "Bhavesh Jadhav",
    logo: "/assets/PlacementImages/infogain.webp",
    companyName: "infogain",
    role: "DevOps Trainee",
  },
  {
    id: 8,
    profilePic: "/assets/PlacementImages/TechnicalSupport.webp",
    username: "Kuldeep Patil",
    logo: "/assets/PlacementImages/leapot.webp",
    companyName: "leapot",
    role: "Technical Support",
  },
  {
    id: 9,
    profilePic: "/assets/PlacementImages/nodejsintern.webp",
    username: "Manish Yelem",
    logo: "/assets/PlacementImages/ovtpl1.webp",
    companyName: "ovtpl1",
    role: "Node.js Intern",
  },
  {
    id: 10,
    profilePic: "/assets/PlacementImages/HTMLDeveloper.webp",
    username: "Mohasin Attar",
    logo: "/assets/PlacementImages/transparency.webp",
    companyName: "transparency",
    role: "HTML Developer",
  },
  {
    id: 11,
    profilePic: "/assets/PlacementImages/ITSupport.webp",
    username: "Rohit Joshi",
    logo: "/assets/PlacementImages/hbfuller.webp",
    companyName: "hbfuller",
    role: "IT Support",
  },
  {
    id: 12,
    profilePic: "/assets/PlacementImages/Dataengine.webp",
    username: "Rutika Pawar",
    logo: "/assets/PlacementImages/nablainfotech.webp",
    companyName: "nablainfotech",
    role: "Data Engineer",
  },
  {
    id: 13,
    profilePic: "/assets/PlacementImages/HRRecuiter.webp",
    username: "Tejaswini Ingle",
    logo: "/assets/PlacementImages/kvstaffingservices.webp",
    companyName: "kvstaffingservices",
    role: "HR Recruiter",
  },
  {
    id: 14,
    profilePic: "/assets/PlacementImages/DataScientist.webp",
    username: "Vaishnavi Sonar",
    logo: "/assets/PlacementImages/bulfro.webp",
    companyName: "bulfro",
    role: "Data Scientist Intern",
  },
  {
    id: 15,
    profilePic: "/assets/PlacementImages/SapExecutive.webp",
    username: "Yash Kurhade",
    logo: "/assets/PlacementImages/faber.webp",
    companyName: "faber",
    role: "SAP Sr. Executive",
  },
  {
    id: 16,
    profilePic: "/assets/PlacementImages/ITDepartment.webp",
    username: "Priyanka Jyoti",
    logo: "/assets/PlacementImages/tatacommunications.webp",
    companyName: "tatacommunications",
    role: "IT Support",
  },
  {
    id: 17,
    profilePic: "/assets/PlacementImages/SoftwareDeveloper.webp",
    username: "Vinayak Sutar",
    logo: "/assets/PlacementImages/bulfro.webp",
    companyName: "bulfro",
    role: "Software Developer",
  },
  {
    id: 18,
    profilePic: "/assets/PlacementImages/CloudTraineeEng.webp",
    username: "Karan Nawale",
    logo: "/assets/PlacementImages/moschip.webp",
    companyName: "moschip",
    role: "Cloud Trainee Engineer",
  },
  {
    id: 19,
    profilePic: "/assets/PlacementImages/PayrollExecutive.webp",
    username: "Ashwini Akshay Swami",
    logo: "/assets/PlacementImages/TopsourceWorldwide.webp",
    companyName: "topsource",
    role: "Payroll Executive",
  },
  {
    id: 20,
    profilePic: "/assets/PlacementImages/AssociateEngineer.webp",
    username: "Rishabh Patond",
    logo: "/assets/PlacementImages/tatacommunications.webp",
    companyName: "tatacommunications",
    role: "Associate Engineer",
  },
  {
    id: 21,
    profilePic: "/assets/PlacementImages/MernStackDeveloperIntern.webp",
    username: "Abhijit Shirsath",
    logo: "/assets/PlacementImages/Provaantech.webp",
    companyName: "provsantech",
    role: "Mern Stack Developer Intern",
  },
  {
    id: 22,
    profilePic: "/assets/PlacementImages/ReactJSIntern.webp",
    username: "Abhishek Mane",
    logo: "/assets/PlacementImages/SevenMentor.webp",
    companyName: "sevenmentor",
    role: "React-JS Intern",
  },
  {
    id: 23,
    profilePic: "/assets/PlacementImages/PythonDeveloper.webp",
    username: "Ajay Kannojwar",
    logo: "/assets/PlacementImages/KarnexAutomotiveSoftwareSolutions.webp",
    companyName: "Karnex – Automotive Software Solutions",
    role: "Python Developer",
  },
  {
    id: 24,
    profilePic: "/assets/PlacementImages/InternAIMLDeveloper.webp",
    username: "Amit Khade",
    logo: "/assets/PlacementImages/Provaantech.webp",
    companyName: "Provaantech",
    role: " Intern AI ML Developer",
  },
  {
    id: 25,
    profilePic: "/assets/PlacementImages/TraineeSOCSupport.webp",
    username: "Bhavika Soni",
    logo: "/assets/PlacementImages/SystemsPlusPrivateLimited.webp",
    companyName: "Systems Plus Private Limited",
    role: "Trainee SOC Support",
  },
  {
    id: 26,
    profilePic: "/assets/PlacementImages/NocEngineer.webp",
    username: "Komal Maruti Shinde",
    logo: "/assets/PlacementImages/GracewayInfrastructure.webp",
    companyName: "Graceway Infrastructure",
    role: " Noc Engineer",
  },
  {
    id: 27,
    profilePic: "/assets/PlacementImages/DevOpsProfessional.webp",
    username: "Mahesh Bodkhe",
    logo: "/assets/PlacementImages/OffshoreITMitraPvtLtd.webp",
    companyName: "Offshore IT Mitra Pvt. Ltd",
    role: "DevOps Professional",
  },
  {
    id: 28,
    profilePic: "/assets/PlacementImages/UIUXDesignerIntern.webp",
    username: "Nikhil Solanki",
    logo: "/assets/PlacementImages/SevenMentor.webp",
    companyName: "SevenMentor Pvt. Ltd",
    role: "UI-UX Designer Intern",
  },
  {
    id: 29,
    profilePic: "/assets/PlacementImages/UIUX-DesignerIntern.webp",
    username: "Pornima Joshi",
    logo: "/assets/PlacementImages/CodingCultCommunity.webp",
    companyName: "Coding Cult Community",
    role: "UI-UX Designer Intern",
  },
  {
    id: 30,
    profilePic: "/assets/PlacementImages/Intern-AI-ML-developer.webp",
    username: "Pushpendra  Dhamanya",
    logo: "/assets/PlacementImages/Provaantech.webp",
    companyName: "Provaantech",
    role: "Intern AI ML Developer",
  },
  {
    id: 31,
    profilePic: "/assets/PlacementImages/Noc-Engineer.webp",
    username: "Rohit Vilas Londhe",
    logo: "/assets/PlacementImages/GracewayInfrastructure.webp",
    companyName: "Graceway Infrastructure",
    role: "Noc Engineer",
  },
  {
    id: 32,
    profilePic: "/assets/PlacementImages/TalentacquisitionSpecialist.webp",
    username: "Sagar Katkar",
    logo: "/assets/PlacementImages/kvstaffingservices.webp",
    companyName: "KV Staffing Services",
    role: "Talent Acquisition Specialist",
  },
  {
    id: 33,
    profilePic: "/assets/PlacementImages/AssociateELearningDeveloper.webp",
    username: "Suhani Khandelwal",
    logo: "/assets/PlacementImages/leapot.webp",
    companyName: "Leapot Technologies",
    role: "Associate eLearning Developer",
  },
  {
    id: 34,
    profilePic: "/assets/PlacementImages/Associate-Engineer.webp",
    username: "Suraj Chamate",
    logo: "/assets/PlacementImages/tatacommunications.webp",
    companyName: "Tata Communications",
    role: "Associate Engineer",
  },
  {
    id: 35,
    profilePic: "/assets/PlacementImages/Mern-stack-developer-intern.webp",
    username: "Akshada Khese",
    logo: "/assets/PlacementImages/Provaantech.webp",
    companyName: "Provaantech",
    role: "Mern Stack Developer Intern",
  },
  {
    id: 36,
    profilePic: "/assets/PlacementImages/Mernstack-developerintern.webp",
    username: "Akshay Gadade ",
    logo: "/assets/PlacementImages/Provaantech.webp",
    companyName: "Provaantech",
    role: "Mern Stack Developer Intern",
  },
  {
    id: 37,
    profilePic: "/assets/PlacementImages/UIUXdesigner-intern.webp",
    username: "Megha Nejkar",
    logo: "/assets/PlacementImages/Provaantech.webp",
    companyName: "Provaantech",
    role: "UI-UX Designer Intern",
  },
  {
    id: 38,
    profilePic: "/assets/PlacementImages/ui-uxdesignerintern.webp",
    username: "Parth Ingle",
    logo: "/assets/PlacementImages/Provaantech.webp",
    companyName: "Provaantech",
    role: "UI-UX Designer Intern",
  },
  {
    id: 39,
    profilePic: "/assets/PlacementImages/uiux-designerIntern-.webp",
    username: "Sakshi Karanjkar",
    logo: "/assets/PlacementImages/BluePearlHealthTechpvtltd..webp",
    companyName: "Provaantech",
    role: "UI-UX Designer Intern",
  },
  {
    id: 40,
    profilePic: "/assets/PlacementImages/uIuX-designer-Intern-.webp",
    username: "Sakshi Tamgade",
    logo: "/assets/PlacementImages/Provaantech.webp",
    companyName: "Provaantech",
    role: "UI-UX Designer Intern",
  },
  {
    id: 41,
    profilePic: "/assets/PlacementImages/TraineeSoftwareEngineer.webp",
    username: "Amol Pawar",
    logo: "/assets/PlacementImages/DigiAlpha.webp",
    companyName: "Digialpha",
    role: "Trainee Software Engineer",
  },
  {
    id: 42,
    profilePic: "/assets/PlacementImages/AssociateFullStackDeveloper.webp",
    username: "Yash Bagewadikar",
    logo: "/assets/PlacementImages/CodingCultCommunity.webp",
    companyName: "Coding Cult Community",
    role: "Jr Associate (Full Stack Developer)",
  },
  {
    id: 43,
    profilePic: "/assets/PlacementImages/Mernstackdeveloperintern4.webp",
    username: "Rajat Gautam",
    logo: "/assets/PlacementImages/Provaantech.webp",
    companyName: "Provaantech",
    role: "MERN Stack Developer Intern",
  },
  {
    id: 44,
    profilePic: "/assets/PlacementImages/FaizanSheikhSoftwaredeveloperIntern.webp",
    username: "Faizan Sheikh",
    logo: "/assets/PlacementImages/PawarTechnologies.webp",
    companyName: "Pawar Technologies",
    role: "Software Developer Intern",
  },
  {
    id: 45,
    profilePic: "/assets/PlacementImages/RichaWadekarQAEngineer.webp",
    username: "Richa Wadekar",
    logo: "/assets/PlacementImages/MindbowserInc.webp",
    companyName: "Mindbowser Inc",
    role: "QA Engineer",
  },
    {
    id: 46,
    profilePic: "/assets/PlacementImages/NikitaShindeQualityAnalystIntern.webp",
    username: "Nikita Shinde",
    logo: "/assets/PlacementImages/ThinkitiveTechnologiesPrivateLimited.webp",
    companyName: "Thinkitive Technologies",
    role: "Quality Analyst Intern",
  },
  {
    id: 47,
    profilePic: "/assets/PlacementImages/MayuripatilJrQAEngineer.webp",
    username: "Mayuri Patil",
    logo: "/assets/PlacementImages/SanchiSolutionsPvtLtd.webp",
    companyName: "Sanchi Solution Pvt Ltd",
    role: "Jr QA Engineer",
  },
   {
    id: 48,
    profilePic: "/assets/PlacementImages/HarshadShindeQualityAnalyst.webp",
    username: "Harshad Shinde",
    logo: "/assets/PlacementImages/nimapinfotech.webp",
    companyName: "Nimap Infotech",
    role: "Quality Analyst",
  },
   {
    id: 49,
    profilePic: "/assets/PlacementImages/AnuragSulkiyaFullStackIntern.webp",
    username: "Anurag Sulkiya",
    logo: "/assets/PlacementImages/Procurpalpvtltd.webp",
    companyName: "Procurpal pvt ltd",
    role: "FullStack Intern",
  },
  {
    id: 50,
    profilePic: "/assets/PlacementImages/SourabhKedarFullStackIntern.webp",
    username: "Sourabh Kedar",
    logo: "/assets/PlacementImages/Procurpalpvtltd.webp",
    companyName: "Procurpal pvt ltd",
    role: "FullStack Intern",
  },
  {
    id: 51,
    profilePic: "/assets/PlacementImages/SachinShewaleGraphicsDesignerIntern.webp",
    username: "Sachin Shewale",
    logo: "/assets/PlacementImages/SevenMentor.webp",
    companyName: "SevenMentor Pvt Ltd",
    role: "Graphics Designer Intern",
  },
    {
    id: 52,
    profilePic: "/assets/PlacementImages/PavanVaishnavWebDeveloper.webp",
    username: "Pavan Vaishnav",
    logo: "/assets/PlacementImages/Dossiefoyerprivatelimited.webp",
    companyName: "Dossiefoyer pvt ltd",
    role: "Web Developer",
  },
  {
    id: 53,
    profilePic: "/assets/PlacementImages/RahulTuwarUIUXDesigner.webp",
    username: "Rahul Tuwar",
    logo: "/assets/PlacementImages/SatishInfotechpvtltd.webp",
    companyName: "Satish Infotech pvt ltd",
    role: "UI UX Designer",
  },
   {
    id: 54,
    profilePic: "/assets/PlacementImages/ParthGordeFrontendDeveloper.webp",
    username: "Parth Gorde",
    logo: "/assets/PlacementImages/Engineer_sCradle.webp",
    companyName: "Engineer_s Cradle",
    role: "Frontend Developer",
  },
  {
    id: 55,
    profilePic: "/assets/PlacementImages/AKASHLOKHANDENetworkEnginner.webp",
    username: "Akash Lokhande",
    logo: "/assets/PlacementImages/NelitoSystemsPrivateLimited.webp",
    companyName: "Nelito Systems Pvt ltd",
    role: "Network Enginner",
  },
    {
    id: 56,
    profilePic: "/assets/PlacementImages/VaishnaviPadwalFullstackDeveloperIntern.webp",
    username: "Vaishnavi Padwal",
    logo: "/assets/PlacementImages/inditronics.webp",
    companyName: "Inditronics Pvt ltd",
    role: "Fullstack Developer Intern",
  },
  {
    id: 57,
    profilePic: "/assets/PlacementImages/AnushriFrontendDeveloper.webp",
    username: "Anushri Bindod",
    logo: "/assets/PlacementImages/CleverGroundTechnologiesPvt.webp",
    companyName: "CleverGround Technologies Pvt ltd",
    role: "Frontend Developer",
  },
    {
    id: 58,
    profilePic: "/assets/PlacementImages/YashodipvijaypatilTechnicalSupportEngineeer.webp",
    username: "Yashodip Vijay Patil",
    logo: "/assets/PlacementImages/AccelItServices.webp",
    companyName: "Accel It Services",
    role: "Technical Support Engineeer",
  },
  {
    id: 59,
    profilePic: "/assets/PlacementImages/VaibhavSantoshGirguneReactDeveloper.webp",
    username: "Vaibhav Santosh Girgune",
    logo: "/assets/PlacementImages/NexgensisTechnologiesPvtLtd.webp",
    companyName: "Nexgensis Technologies Pvt Ltd",
    role: "React Developer",
  },
   {
    id: 60,
    profilePic: "/assets/PlacementImages/TejaswiniPawarSoftwareDeveloper.webp",
    username: "Tejaswini Pawar",
    logo: "/assets/PlacementImages/uniinfosolutionsPvtLtd.webp",
    companyName: "Uniinfo Solutions Pvt Ltd",
    role: "Software Developer",
  },
  {
    id: 61,
    profilePic: "/assets/PlacementImages/SarveshKaleDeveloper.webp",
    username: "Sarvesh Kale",
    logo: "/assets/PlacementImages/PraxisInfoSolutionsPvtLtd.webp",
    companyName: "Praxis Info Solutions Pvt Ltd",
    role: "Trainee Developer",
  },
  {
    id: 62,
    profilePic: "/assets/PlacementImages/SAMARJEETSAODataLabellingIntern.webp",
    username: "Samarjeet Sao",
    logo: "/assets/PlacementImages/inditronics.webp",
    companyName: "Inditronix",
    role: "Data Labelling Intern",
  },
   {
    id: 63,
    profilePic: "/assets/PlacementImages/PrathameshJadhavEngineer.webp",
    username: "Prathemesh Jadhav",
    logo: "/assets/PlacementImages/Airtel.webp",
    companyName: "Airtel",
    role: "Engineer",
  },
   {
    id: 64,
    profilePic: "/assets/PlacementImages/MugdhaLabhadeSoftwareDeveloperIntern.webp",
    username: "Mugdha Labhade",
    logo: "/assets/PlacementImages/AutoAppy.webp",
    companyName: "Auto Appy",
    role: "Software Developer Intern",
  },
  {
    id: 65,
    profilePic: "/assets/PlacementImages/ASHISHGAIKWADJuniorSOCAnalyst.webp",
    username: "Ashish Gaikwad",
    logo: "/assets/PlacementImages/Cloudin.webp",
    companyName: "Cloud.in",
    role: "Junior SOC Analyst",
  },
   {
    id: 66,
    profilePic: "/assets/PlacementImages/RUTUJAKAMBLECyberSecurityEngineer.webp",
    username: "Rutuja Kamble",
    logo: "/assets/PlacementImages/SystemsPlus.webp",
    companyName: "System Plus",
    role: "Cyber Security Engineer",
  },
  {
    id: 67,
    profilePic: "/assets/PlacementImages/ManthanSatheCyberSecurityEngineer.webp",
    username: "Manthan Sathe",
    logo: "/assets/PlacementImages/SystemsPlus.webp",
    companyName: "System Plus",
    role: "Cyber Security Engineer",
  },
  {
    id: 68,
    profilePic: "/assets/PlacementImages/ShreyasChavanCMSExecutive.webp",
    username: "Shreyas Chavan",
    logo: "/assets/PlacementImages/IntegratedActiveMonitoringPvtLtd.webp",
    companyName: "Integrated Active Monitoring Pvt Ltd",
    role: "CMS Executive",
  },
  {
    id: 69,
    profilePic: "/assets/PlacementImages/AniketPatilFullstackWebDeveloper.webp",
    username: "Aniket Patil",
    logo: "/assets/PlacementImages/PUBMIGHTYPRIVATELIMITED.webp",
    companyName: "Pubmighty Pvt Ltd",
    role: "FullStack Web Developer",
  },
  {
    id: 70,
    profilePic: "/assets/PlacementImages/YashitaPachauriDesignandEstimationEngineer.webp",
    username: "Yashita Pachauri",
    logo: "/assets/PlacementImages/CyberneticsSoftwarePvtLtd.webp",
    companyName: "Cybernetics Software Pvt Ltd",
    role: "Design & Estimation Engineer",
  },
  {
    id: 71,
    profilePic: "/assets/PlacementImages/UjwalaBhaleraoWebDevelopment.webp",
    username: "Ujwala Bhalerao",
    logo: "/assets/PlacementImages/JindanTechnology.webp",
    companyName: "Jindan Technology",
    role: "Web Developer",
  },
  {
    id: 72,
    profilePic: "/assets/PlacementImages/krishnashindeFrontEndDeveloper.webp",
    username: "Krishna Shinde",
    logo: "/assets/PlacementImages/CleverGroundTechnologiesPvt.webp",
    companyName: "CleverGround Technologies Pvt Ltd",
    role: "FrontEnd Developer",
  },
  {
    id: 73,
    profilePic: "/assets/PlacementImages/GauravKarajgikarReactJsDevelopment.webp",
    username: "Gaurav Karajgikar",
    logo: "/assets/PlacementImages/leapot.webp",
    companyName: "Leapot Technologies",
    role: "ReactJs Developer",
  },
   {
    id: 74,
    profilePic: "/assets/PlacementImages/ASHWINIKHANDAGALEUI_UXDesigner.webp",
    username: "Ashwini Khandagale",
    logo: "/assets/PlacementImages/Lumenithtechnologies.webp",
    companyName: "Lumenith Technologies",
    role: "UI-UX Designer",
  },
  {
    id: 75,
    profilePic: "/assets/PlacementImages/AkashBhiseWebDevelopment.webp",
    username: "Akash Bhise",
    logo: "/assets/PlacementImages/JindanTechnology.webp",
    companyName: "Jindan Technology",
    role: "Web Developer",
  },
   {
    id: 76,
    profilePic: "/assets/PlacementImages/AarohiMhaisalkarAIAgentDevelopment.webp",
    username: "Aarohi Mhaisalkar",
    logo: "/assets/PlacementImages/leapot.webp",
    companyName: "Leapot Technologies",
    role: "AI Agent Developer",
  },
  {
    id: 77,
    profilePic: "/assets/PlacementImages/VivekBisenReactJsDeveloper.webp",
    username: "Vivek Bisen",
    logo: "/assets/PlacementImages/OS3INFOTECHPVTLTD.webp",
    companyName: "OS3 INFOTECH PVT LTD",
    role: "ReactJs Developer",
  },
  {
    id: 78,
    profilePic: "/assets/PlacementImages/ShalmaliIngawaleHRExecutive.webp",
    username: "Shalmali Ingawale",
    logo: "/assets/PlacementImages/GlowbeatAdvisor.webp",
    companyName: "Glowbeat Advisor",
    role: "HR Executive",
  },
  {
    id: 79,
    profilePic: "/assets/PlacementImages/SakshiTongaleRPAEngineer.webp",
    username: "Sakshi Tongale",
    logo: "/assets/PlacementImages/IntelligentDX.webp",
    companyName: "IntelligentDX",
    role: "RPA Engineer",
  },
  {
    id: 80,
    profilePic: "/assets/PlacementImages/PoojaJadhavRPAEngineer.webp",
    username: "Pooja Jadhav",
    logo: "/assets/PlacementImages/IntelligentDX.webp",
    companyName: "IntelligentDX",
    role: "RPA Engineer",
  },
  {
    id: 81,
    profilePic: "/assets/PlacementImages/SHANTANUTUPKARRPAEngineer.webp",
    username: "Shantanu Tupkar",
    logo: "/assets/PlacementImages/IntelligentDX.webp",
    companyName: "IntelligentDX",
    role: "RPA Engineer",
  },
  {
    id: 82,
    profilePic: "/assets/PlacementImages/JiveshBharambeRPAEngineer.webp",
    username: "Jivesh Bharambe",
    logo: "/assets/PlacementImages/IntelligentDX.webp",
    companyName: "IntelligentDX",
    role: "RPA Engineer",
  },
  {
    id: 83,
    profilePic: "/assets/PlacementImages/ChinmayBagalRPAEngineer.webp",
    username: "Chinmay Bagal",
    logo: "/assets/PlacementImages/IntelligentDX.webp",
    companyName: "IntelligentDX",
    role: "RPA Engineer",
  },
];

export default PlacedStudentsData;
