// Course, Statistic, and Feature data structures

export const statistics = [
    { id: 1, value: "10+", label: "Years of Excellence" },
    { id: 2, value: "5000+", label: "Students Trained" },
    { id: 3, value: "50+", label: "Expert Trainers" },
    { id: 4, value: "95%", label: "Placement Record" },
];

export const features = [
    {
        id: 1,
        icon: "Award",
        title: "Certified Training",
        description: "Get industry-recognized certifications upon course completion",
    },
    {
        id: 2,
        icon: "Users",
        title: "Expert Trainers",
        description: "Learn from experienced professionals with real-world expertise",
    },
    {
        id: 3,
        icon: "Clock",
        title: "Flexible Timings",
        description: "Choose from weekday, weekend, and fast-track batches",
    },
    {
        id: 4,
        icon: "Briefcase",
        title: "100% Job Support",
        description: "Comprehensive placement assistance and career guidance",
    },
];

export const courses = [
    // Popular Courses
    {
        id: 1,
        title: "Java Training",
        description: "Master Java programming from basics to advanced concepts. Learn object-oriented programming, data structures, and build real-world applications with industry best practices.",
        category: "Popular",
        rating: 4.8,
        reviews: 245,
        price: 15000,
        duration: "3 Months",
        level: "Beginner to Advanced",
        badge: "Bestseller",
    },
    {
        id: 2,
        title: "Python Training",
        description: "Learn Python programming for web development, data analysis, and automation. Master Django, Flask, and popular Python libraries to build powerful applications.",
        category: "Popular",
        rating: 4.9,
        reviews: 312,
        price: 18000,
        duration: "3 Months",
        level: "All Levels",
        badge: "Bestseller",
    },
    {
        id: 3,
        title: "AWS Training",
        description: "Become an AWS certified professional. Learn cloud computing, EC2, S3, Lambda, and deploy scalable applications on Amazon Web Services infrastructure.",
        category: "Popular",
        rating: 4.7,
        reviews: 198,
        price: 22000,
        duration: "2 Months",
        level: "Intermediate",
    },
    {
        id: 4,
        title: "Data Science",
        description: "Transform your career with comprehensive data science training. Master Python, R, machine learning, statistics, and data visualization to become a data scientist.",
        category: "Popular",
        rating: 4.9,
        reviews: 287,
        price: 35000,
        duration: "6 Months",
        level: "Advanced",
        badge: "Bestseller",
    },
    {
        id: 5,
        title: "Full Stack Development",
        description: "Become a complete full stack developer. Learn HTML, CSS, JavaScript, React, Node.js, databases, and build end-to-end web applications from scratch.",
        category: "Popular",
        rating: 4.8,
        reviews: 223,
        price: 40000,
        duration: "6 Months",
        level: "All Levels",
    },
    {
        id: 6,
        title: "React JS Training",
        description: "Master React.js and build modern, interactive user interfaces. Learn components, hooks, state management, Redux, and create dynamic single-page applications.",
        category: "Popular",
        rating: 4.7,
        reviews: 176,
        price: 16000,
        duration: "2 Months",
        level: "Intermediate",
    },
    {
        id: 101,
        title: "JavaScript Mastery",
        description: "Deep dive into JavaScript fundamentals and advanced concepts. Learn ES6+, async programming, closures, and modern JavaScript development techniques.",
        category: "Popular",
        rating: 4.8,
        reviews: 198,
        price: 14000,
        duration: "2 Months",
        level: "All Levels",
    },
    {
        id: 102,
        title: "SQL & Database Management",
        description: "Master SQL queries and database design. Learn MySQL, PostgreSQL, database optimization, and build efficient data-driven applications.",
        category: "Popular",
        rating: 4.6,
        reviews: 167,
        price: 12000,
        duration: "2 Months",
        level: "Beginner to Intermediate",
    },
    {
        id: 103,
        title: "Digital Marketing",
        description: "Become a digital marketing expert. Learn SEO, SEM, social media marketing, content marketing, and drive business growth through digital channels.",
        category: "Popular",
        rating: 4.7,
        reviews: 234,
        price: 18000,
        duration: "3 Months",
        level: "All Levels",
        badge: "Bestseller",
    },

    // Trending Courses
    {
        id: 7,
        title: "Cyber Security",
        description: "Protect organizations from cyber threats. Learn ethical hacking, network security, penetration testing, and security best practices to become a cybersecurity expert.",
        category: "Trending",
        rating: 4.8,
        reviews: 189,
        price: 28000,
        duration: "4 Months",
        level: "Intermediate",
        badge: "Trending",
    },
    {
        id: 8,
        title: "DevOps Training",
        description: "Master DevOps practices and tools. Learn CI/CD, Docker, Kubernetes, Jenkins, Git, and automate software development and deployment processes.",
        category: "Trending",
        rating: 4.7,
        reviews: 165,
        price: 25000,
        duration: "3 Months",
        level: "Advanced",
        badge: "Trending",
    },
    {
        id: 9,
        title: "Machine Learning",
        description: "Dive deep into machine learning algorithms and AI. Learn supervised and unsupervised learning, neural networks, and build intelligent systems that learn from data.",
        category: "Trending",
        rating: 4.9,
        reviews: 234,
        price: 38000,
        duration: "5 Months",
        level: "Advanced",
    },
    {
        id: 104,
        title: "Artificial Intelligence",
        description: "Explore the world of AI and deep learning. Master neural networks, NLP, computer vision, and build cutting-edge AI applications.",
        category: "Trending",
        rating: 4.9,
        reviews: 201,
        price: 42000,
        duration: "6 Months",
        level: "Advanced",
        badge: "Bestseller",
    },
    {
        id: 105,
        title: "Blockchain Development",
        description: "Learn blockchain technology and smart contracts. Master Ethereum, Solidity, Web3.js, and build decentralized applications on blockchain.",
        category: "Trending",
        rating: 4.6,
        reviews: 143,
        price: 32000,
        duration: "4 Months",
        level: "Intermediate",
        badge: "Trending",
    },
    {
        id: 106,
        title: "Cloud Computing",
        description: "Master cloud platforms and services. Learn AWS, Azure, Google Cloud, cloud architecture, and deploy scalable cloud solutions.",
        category: "Trending",
        rating: 4.8,
        reviews: 178,
        price: 26000,
        duration: "3 Months",
        level: "Intermediate",
    },
    {
        id: 107,
        title: "IoT Development",
        description: "Build Internet of Things solutions. Learn Arduino, Raspberry Pi, sensors, connectivity protocols, and create smart IoT devices.",
        category: "Trending",
        rating: 4.5,
        reviews: 112,
        price: 24000,
        duration: "3 Months",
        level: "Intermediate",
    },
    {
        id: 108,
        title: "Flutter App Development",
        description: "Create beautiful cross-platform mobile apps with Flutter. Learn Dart, widgets, state management, and build iOS and Android apps from a single codebase.",
        category: "Trending",
        rating: 4.7,
        reviews: 156,
        price: 20000,
        duration: "3 Months",
        level: "Intermediate",
        badge: "Trending",
    },

    // Networking Courses
    {
        id: 10,
        title: "CCNA Training",
        description: "Start your networking career with Cisco CCNA certification. Learn network fundamentals, routing, switching, IP addressing, and network security basics.",
        category: "Networking",
        rating: 4.6,
        reviews: 142,
        price: 18000,
        duration: "2 Months",
        level: "Beginner",
    },
    {
        id: 11,
        title: "CCNP Training",
        description: "Advance your networking skills with CCNP certification. Master advanced routing, switching, troubleshooting, and enterprise network solutions.",
        category: "Networking",
        rating: 4.7,
        reviews: 98,
        price: 25000,
        duration: "3 Months",
        level: "Advanced",
    },
    {
        id: 12,
        title: "Network Security",
        description: "Secure network infrastructure from threats. Learn firewalls, VPNs, intrusion detection, network monitoring, and implement robust security measures.",
        category: "Networking",
        rating: 4.5,
        reviews: 87,
        price: 22000,
        duration: "2 Months",
        level: "Intermediate",
    },
    {
        id: 109,
        title: "CompTIA Network+",
        description: "Get CompTIA Network+ certified. Learn networking concepts, infrastructure, operations, security, and troubleshooting for IT professionals.",
        category: "Networking",
        rating: 4.6,
        reviews: 134,
        price: 16000,
        duration: "2 Months",
        level: "Beginner",
    },
    {
        id: 110,
        title: "Wireless Networking",
        description: "Master wireless network technologies. Learn WiFi standards, wireless security, access points, and design robust wireless networks.",
        category: "Networking",
        rating: 4.5,
        reviews: 89,
        price: 19000,
        duration: "2 Months",
        level: "Intermediate",
    },
    {
        id: 111,
        title: "Network Administration",
        description: "Become a network administrator. Learn network management, server administration, Active Directory, and maintain enterprise networks.",
        category: "Networking",
        rating: 4.7,
        reviews: 156,
        price: 21000,
        duration: "3 Months",
        level: "Intermediate",
    },

    // Software Courses
    {
        id: 13,
        title: "Angular Training",
        description: "Build powerful web applications with Angular. Learn TypeScript, components, services, routing, and create enterprise-level single-page applications.",
        category: "Software",
        rating: 4.6,
        reviews: 156,
        price: 16000,
        duration: "2 Months",
        level: "Intermediate",
    },
    {
        id: 14,
        title: "Node.js Training",
        description: "Master server-side JavaScript with Node.js. Learn Express.js, REST APIs, database integration, and build scalable backend applications.",
        category: "Software",
        rating: 4.7,
        reviews: 189,
        price: 18000,
        duration: "2 Months",
        level: "Intermediate",
    },
    {
        id: 15,
        title: "Software Testing",
        description: "Become a quality assurance expert. Learn manual and automated testing, Selenium, test frameworks, and ensure software quality and reliability.",
        category: "Software",
        rating: 4.8,
        reviews: 203,
        price: 15000,
        duration: "3 Months",
        level: "Beginner",
    },
    {
        id: 112,
        title: "Vue.js Development",
        description: "Create modern web apps with Vue.js. Learn Vue components, Vuex, Vue Router, and build reactive single-page applications.",
        category: "Software",
        rating: 4.6,
        reviews: 145,
        price: 15000,
        duration: "2 Months",
        level: "Intermediate",
    },
    {
        id: 113,
        title: "Spring Boot",
        description: "Build enterprise Java applications with Spring Boot. Learn microservices, REST APIs, Spring Security, and create production-ready applications.",
        category: "Software",
        rating: 4.8,
        reviews: 167,
        price: 22000,
        duration: "3 Months",
        level: "Advanced",
    },
    {
        id: 114,
        title: ".NET Development",
        description: "Master .NET framework and C#. Learn ASP.NET Core, MVC, Web APIs, and build robust enterprise applications on Microsoft stack.",
        category: "Software",
        rating: 4.7,
        reviews: 178,
        price: 20000,
        duration: "3 Months",
        level: "Intermediate",
    },
    {
        id: 115,
        title: "PHP & Laravel",
        description: "Develop dynamic websites with PHP and Laravel. Learn MVC architecture, Eloquent ORM, authentication, and build modern web applications.",
        category: "Software",
        rating: 4.5,
        reviews: 134,
        price: 14000,
        duration: "2 Months",
        level: "Beginner to Intermediate",
    },
    {
        id: 116,
        title: "Mobile App Development",
        description: "Create native mobile apps for iOS and Android. Learn Swift, Kotlin, mobile UI/UX, and publish apps to app stores.",
        category: "Software",
        rating: 4.7,
        reviews: 189,
        price: 28000,
        duration: "4 Months",
        level: "Intermediate",
    },

    // Data Science Courses
    {
        id: 16,
        title: "Data Analytics",
        description: "Analyze and interpret complex data sets. Learn SQL, Excel, Tableau, Power BI, and transform data into actionable business insights.",
        category: "Data Science",
        rating: 4.8,
        reviews: 267,
        price: 32000,
        duration: "4 Months",
        level: "All Levels",
    },
    {
        id: 17,
        title: "Big Data Hadoop",
        description: "Handle massive datasets with Hadoop ecosystem. Learn HDFS, MapReduce, Hive, Pig, and process big data efficiently at scale.",
        category: "Data Science",
        rating: 4.7,
        reviews: 145,
        price: 30000,
        duration: "3 Months",
        level: "Advanced",
    },
    {
        id: 18,
        title: "Power BI Training",
        description: "Create stunning data visualizations with Power BI. Learn DAX, data modeling, interactive dashboards, and deliver impactful business intelligence reports.",
        category: "Data Science",
        rating: 4.6,
        reviews: 198,
        price: 14000,
        duration: "1 Month",
        level: "Beginner",
    },
    {
        id: 117,
        title: "Tableau Training",
        description: "Master data visualization with Tableau. Create interactive dashboards, perform data analysis, and communicate insights effectively.",
        category: "Data Science",
        rating: 4.7,
        reviews: 176,
        price: 15000,
        duration: "1.5 Months",
        level: "Beginner",
    },
    {
        id: 118,
        title: "R Programming",
        description: "Learn statistical computing with R. Master data manipulation, statistical analysis, machine learning, and data visualization in R.",
        category: "Data Science",
        rating: 4.6,
        reviews: 134,
        price: 18000,
        duration: "2 Months",
        level: "Intermediate",
    },
    {
        id: 119,
        title: "Apache Spark",
        description: "Process big data with Apache Spark. Learn Spark SQL, Spark Streaming, MLlib, and build fast, distributed data processing applications.",
        category: "Data Science",
        rating: 4.8,
        reviews: 123,
        price: 28000,
        duration: "3 Months",
        level: "Advanced",
    },
    {
        id: 120,
        title: "Deep Learning",
        description: "Master deep neural networks and AI. Learn TensorFlow, Keras, CNNs, RNNs, and build advanced deep learning models.",
        category: "Data Science",
        rating: 4.9,
        reviews: 156,
        price: 40000,
        duration: "5 Months",
        level: "Advanced",
    },

    // SAP Courses
    {
        id: 19,
        title: "SAP FICO",
        description: "Master SAP Financial Accounting and Controlling. Learn general ledger, accounts payable/receivable, cost center accounting, and financial reporting.",
        category: "SAP",
        rating: 4.5,
        reviews: 123,
        price: 35000,
        duration: "3 Months",
        level: "Intermediate",
    },
    {
        id: 20,
        title: "SAP MM",
        description: "Become an SAP Materials Management expert. Learn procurement, inventory management, vendor management, and material planning processes.",
        category: "SAP",
        rating: 4.6,
        reviews: 98,
        price: 32000,
        duration: "3 Months",
        level: "Intermediate",
    },
    {
        id: 21,
        title: "SAP SD",
        description: "Master SAP Sales and Distribution module. Learn order management, pricing, billing, shipping, and streamline sales processes in SAP.",
        category: "SAP",
        rating: 4.4,
        reviews: 87,
        price: 30000,
        duration: "3 Months",
        level: "Intermediate",
    },
    {
        id: 121,
        title: "SAP HR/HCM",
        description: "Learn SAP Human Capital Management. Master personnel administration, payroll, time management, and organizational management in SAP.",
        category: "SAP",
        rating: 4.5,
        reviews: 109,
        price: 33000,
        duration: "3 Months",
        level: "Intermediate",
    },
    {
        id: 122,
        title: "SAP ABAP",
        description: "Become an SAP ABAP programmer. Learn ABAP programming, data dictionary, reports, forms, and customize SAP applications.",
        category: "SAP",
        rating: 4.7,
        reviews: 145,
        price: 36000,
        duration: "4 Months",
        level: "Advanced",
    },
    {
        id: 123,
        title: "SAP S/4HANA",
        description: "Master SAP's next-generation ERP. Learn S/4HANA architecture, Fiori apps, migration strategies, and implement modern SAP solutions.",
        category: "SAP",
        rating: 4.8,
        reviews: 167,
        price: 45000,
        duration: "4 Months",
        level: "Advanced",
    },
    {
        id: 124,
        title: "SAP Basis",
        description: "Become an SAP Basis administrator. Learn system administration, database management, performance tuning, and maintain SAP landscapes.",
        category: "SAP",
        rating: 4.6,
        reviews: 112,
        price: 34000,
        duration: "3 Months",
        level: "Intermediate",
    },

    // CAD Courses
    {
        id: 22,
        title: "AutoCAD 2D/3D",
        description: "Design with precision using AutoCAD. Learn 2D drafting, 3D modeling, architectural drawings, and create professional engineering designs.",
        category: "CAD",
        rating: 4.7,
        reviews: 176,
        price: 12000,
        duration: "2 Months",
        level: "Beginner",
    },
    {
        id: 23,
        title: "CATIA Training",
        description: "Master CATIA for advanced product design. Learn parametric modeling, surface design, assembly, and create complex mechanical components.",
        category: "CAD",
        rating: 4.6,
        reviews: 134,
        price: 18000,
        duration: "3 Months",
        level: "Intermediate",
    },
    {
        id: 24,
        title: "SolidWorks Training",
        description: "Create innovative designs with SolidWorks. Learn 3D CAD modeling, simulation, assembly design, and bring your engineering ideas to life.",
        category: "CAD",
        rating: 4.8,
        reviews: 145,
        price: 16000,
        duration: "2 Months",
        level: "Intermediate",
    },
    {
        id: 125,
        title: "Revit Architecture",
        description: "Master BIM with Revit. Learn architectural modeling, families, rendering, documentation, and create intelligent building designs.",
        category: "CAD",
        rating: 4.7,
        reviews: 156,
        price: 20000,
        duration: "3 Months",
        level: "Intermediate",
    },
    {
        id: 126,
        title: "Creo Parametric",
        description: "Design with PTC Creo. Learn parametric modeling, surfacing, assembly, and create complex product designs for manufacturing.",
        category: "CAD",
        rating: 4.6,
        reviews: 98,
        price: 17000,
        duration: "2.5 Months",
        level: "Intermediate",
    },
    {
        id: 127,
        title: "Fusion 360",
        description: "Create 3D designs with Autodesk Fusion 360. Learn cloud-based CAD/CAM, generative design, simulation, and collaborative product development.",
        category: "CAD",
        rating: 4.7,
        reviews: 123,
        price: 15000,
        duration: "2 Months",
        level: "Beginner to Intermediate",
    },
    {
        id: 128,
        title: "ANSYS Simulation",
        description: "Master engineering simulation with ANSYS. Learn FEA, CFD, structural analysis, thermal analysis, and validate your designs virtually.",
        category: "CAD",
        rating: 4.8,
        reviews: 134,
        price: 25000,
        duration: "3 Months",
        level: "Advanced",
    },
];

export const getCoursesByCategory = (category) => {
    return courses.filter((course) => course.category === category);
};

export const categories = [
    "Popular",
    "Trending",
    "Networking",
    "Software",
    "Data Science",
    "SAP",
    "CAD",
];
